// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccData struct {
	Name     string `json:"name"`
	Usern    string `json:"usern"`
	Password string `json:"password"`
}

type Account struct {
	Name     string `json:"name"`
	Usern    string `json:"usern"`
	Password string `json:"password"`
}

type User struct {
	Email string `json:"email"`
	Data  string `json:"data"`
}
